{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "weblate-operator.fullname" . }}
  labels:
    {{- include "weblate-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "weblate-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "weblate-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
