{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "weblate-operator.fullname" . }}
  labels:
    {{- include "weblate-operator.labels" . | nindent 4 }}
rules:

  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]

  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
{{- end }}
