apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weblate-operator.fullname" . }}
  labels:
    {{- include "weblate-operator.labels" . | nindent 4 }}
data:
  api_url: {{ .Values.config.weblateAPIUrl }}
