apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weblate-operator.fullname" . }}
  labels:
    {{- include "weblate-operator.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.config.weblateAPIKey | b64enc }}
