API_URL = "http://weblate/api/"
PROJECT_NAME = "test-project"
COMPONENT_NAME = "test-component"
TRANSLATION_NAME = "de"

PROJECT_RESPONSE = {
    "name": "test-project",
    "slug": "test-project",
    "id": 12,
    "web": "http://test.project.com",
    "web_url": "http://weblate/projects/test-project/",
    "url": "http://weblate/api/projects/test-project/",
    "components_list_url": "http://weblate/api/projects/test-project/components/",
    "repository_url": "http://weblate/api/projects/test-project/repository/",
    "statistics_url": "http://weblate/api/projects/test-project/statistics/",
    "changes_list_url": "http://weblate/api/projects/test-project/changes/",
    "languages_url": "http://weblate/api/projects/test-project/languages/",
    "translation_review": "false",
    "source_review": "false",
    "set_language_team": "true",
    "instructions": "",
    "enable_hooks": "true",
    "language_aliases": "",
}

COMPONENT_RESPONSE = {
    "name": "test-component",
    "slug": "test-component",
    "id": 8,
    "source_language": {
        "code": "en",
        "name": "English",
        "plural": {"id": 140, "source": 0, "number": 2, "formula": "n != 1", "type": 1},
        "aliases": ["en_en", "base", "source", "enp", "eng"],
        "direction": "ltr",
        "population": 159034349015,
        "web_url": "http://weblate/languages/en/",
        "url": "http://weblate/api/languages/en/",
        "statistics_url": "http://weblate/api/languages/en/statistics/",
    },
    "project": {
        "name": "test-project-patched",
        "slug": "test-project",
        "id": 86,
        "web": "http://weblate.project.example",
        "web_url": "http://weblate/projects/test-project/",
        "url": "http://weblate/api/projects/test-project/",
        "components_list_url": "http://weblate/api/projects/test-project/components/",
        "repository_url": "http://weblate/api/projects/test-project/repository/",
        "statistics_url": "http://weblate/api/projects/test-project/statistics/",
        "changes_list_url": "http://weblate/api/projects/test-project/changes/",
        "languages_url": "http://weblate/api/projects/test-project/languages/",
        "translation_review": "false",
        "source_review": "false",
        "set_language_team": "true",
        "instructions": "",
        "enable_hooks": "true",
        "language_aliases": "",
    },
    "vcs": "git",
    "repo": "https://github.com/WeblateOrg/test",
    "git_export": "http://weblate/git/test-project/test-component/",
    "branch": "main",
    "push_branch": "",
    "filemask": "ts/*.ts",
    "template": "",
    "edit_template": "true",
    "intermediate": "",
    "new_base": "ts/cs.ts",
    "file_format": "ts",
    "license": "",
    "license_url": "null",
    "agreement": "",
    "web_url": "http://weblate/projects/test-project/test-component/",
    "url": "http://weblate/api/components/test-project/test-component/",
    "repository_url": "http://weblate/api/components/test-project/test-component/repository/",
    "translations_url": "http://weblate/api/components/test-project/test-component/translations/",
    "statistics_url": "http://weblate/api/components/test-project/test-component/statistics/",
    "lock_url": "http://weblate/api/components/test-project/test-component/lock/",
    "links_url": "http://weblate/api/components/test-project/test-component/links/",
    "changes_list_url": "http://weblate/api/components/test-project/test-component/changes/",
    "task_url": "null",
    "new_lang": "add",
    "language_code_style": "",
    "push": "",
    "check_flags": "",
    "priority": 100,
    "enforced_checks": [],
    "restricted": "false",
    "repoweb": "",
    "report_source_bugs": "",
    "merge_style": "rebase",
    "commit_message": "Translated using Weblate ({{ language_name }})\n\nCurrently translated at {{ stats.translated_percent }}% ({{ stats.translated }} of {{ stats.all }} strings)\n\nTranslation: {{ project_name }}/{{ component_name }}\nTranslate-URL: {{ url }}",
    "add_message": "Added translation using Weblate ({{ language_name }})\n\n",
    "delete_message": "Deleted translation using Weblate ({{ language_name }})\n\n",
    "merge_message": "Merge branch '{{ component_remote_branch }}' into Weblate.\n\n",
    "addon_message": 'Update translation files\n\nUpdated by "{{ addon_name }}" hook in Weblate.\n\nTranslation: {{ project_name }}/{{ component_name }}\nTranslate-URL: {{ url }}',
    "pull_message": "Translations update from {{ site_title }}\n\nTranslations update from [{{ site_title }}]({{ site_url }}) for [{{ project_name }}/{{ component_name }}]({{url}}).\n\n{% if component_linked_childs %}\nIt also includes following components:\n{% for linked in component_linked_childs %}\n* [{{ linked.project_name }}/{{ linked.name }}]({{ linked.url }})\n{% endfor %}\n{% endif %}\n\nCurrent translation status:\n\n![Weblate translation status]({{widget_url}})\n",
    "allow_translation_propagation": "true",
    "manage_units": "false",
    "enable_suggestions": "true",
    "suggestion_voting": "false",
    "suggestion_autoaccept": 0,
    "push_on_commit": "true",
    "commit_pending_age": 24,
    "auto_lock_error": "true",
    "language_regex": "^[^.]+$",
    "variant_regex": "",
    "addons": [],
    "is_glossary": "false",
    "glossary_color": "silver",
}

TRANSLATION_RESPONSE = {
    "language": {
        "code": "de",
        "name": "German",
        "plural": {"id": 121, "source": 0, "number": 2, "formula": "n != 1", "type": 1},
        "aliases": ["deu", "ger"],
        "direction": "ltr",
        "population": 13464146835,
        "web_url": "http://weblate/languages/de/",
        "url": "http://weblate/api/languages/de/",
        "statistics_url": "http://weblate/api/languages/de/statistics/",
    },
    "component": {
        "name": "test-component",
        "slug": "test-component",
        "id": 39,
        "source_language": {
            "code": "en",
            "name": "English",
            "plural": {
                "id": 148,
                "source": 0,
                "number": 2,
                "formula": "n != 1",
                "type": 1,
            },
            "aliases": ["en_en", "base", "source", "enp", "eng"],
            "direction": "ltr",
            "population": 159034349015,
            "web_url": "http://weblate/languages/en/",
            "url": "http://weblate/api/languages/en/",
            "statistics_url": "http://weblate/api/languages/en/statistics/",
        },
        "project": {
            "name": "test-project",
            "slug": "test-project",
            "id": 34,
            "web": "http://weblate.project.example",
            "web_url": "http://weblate/projects/test-project/",
            "url": "http://weblate/api/projects/test-project/",
            "components_list_url": "http://weblate/api/projects/test-project/components/",
            "repository_url": "http://weblate/api/projects/test-project/repository/",
            "statistics_url": "http://weblate/api/projects/test-project/statistics/",
            "changes_list_url": "http://weblate/api/projects/test-project/changes/",
            "languages_url": "http://weblate/api/projects/test-project/languages/",
            "translation_review": "false",
            "source_review": "false",
            "set_language_team": "true",
            "instructions": "",
            "enable_hooks": "true",
            "language_aliases": "",
        },
        "vcs": "git",
        "repo": "https://github.com/WeblateOrg/test",
        "git_export": "http://weblate/git/test-project/test-component/",
        "branch": "main",
        "push_branch": "",
        "filemask": "ts/*.ts",
        "template": "",
        "edit_template": "true",
        "intermediate": "",
        "new_base": "ts/cs.ts",
        "file_format": "ts",
        "license": "",
        # "license_url": "null",
        "agreement": "",
        "web_url": "http://weblate/projects/test-project/test-component/",
        "url": "http://weblate/api/components/test-project/test-component/",
        "repository_url": "http://weblate/api/components/test-project/test-component/repository/",
        "translations_url": "http://weblate/api/components/test-project/test-component/translations/",
        "statistics_url": "http://weblate/api/components/test-project/test-component/statistics/",
        "lock_url": "http://weblate/api/components/test-project/test-component/lock/",
        "links_url": "http://weblate/api/components/test-project/test-component/links/",
        "changes_list_url": "http://weblate/api/components/test-project/test-component/changes/",
        # "task_url": "null",
        "new_lang": "add",
        "language_code_style": "",
        "push": "",
        "check_flags": "",
        "priority": 100,
        "enforced_checks": [],
        "restricted": "false",
        "repoweb": "",
        "report_source_bugs": "",
        "merge_style": "rebase",
        "commit_message": "Translated using Weblate ({{ language_name }})\n\nCurrently translated at {{ stats.translated_percent }}% ({{ stats.translated }} of {{ stats.all }} strings)\n\nTranslation: {{ project_name }}/{{ component_name }}\nTranslate-URL: {{ url }}",
        "add_message": "Added translation using Weblate ({{ language_name }})\n\n",
        "delete_message": "Deleted translation using Weblate ({{ language_name }})\n\n",
        "merge_message": "Merge branch '{{ component_remote_branch }}' into Weblate.\n\n",
        "addon_message": 'Update translation files\n\nUpdated by "{{ addon_name }}" hook in Weblate.\n\nTranslation: {{ project_name }}/{{ component_name }}\nTranslate-URL: {{ url }}',
        "pull_message": "Translations update from {{ site_title }}\n\nTranslations update from [{{ site_title }}]({{ site_url }}) for [{{ project_name }}/{{ component_name }}]({{url}}).\n\n{% if component_linked_childs %}\nIt also includes following components:\n{% for linked in component_linked_childs %}\n* [{{ linked.project_name }}/{{ linked.name }}]({{ linked.url }})\n{% endfor %}\n{% endif %}\n\nCurrent translation status:\n\n![Weblate translation status]({{widget_url}})\n",
        "allow_translation_propagation": "true",
        "manage_units": "false",
        "enable_suggestions": "true",
        "suggestion_voting": "false",
        "suggestion_autoaccept": 0,
        "push_on_commit": "true",
        "commit_pending_age": 24,
        "auto_lock_error": "true",
        "language_regex": "^[^.]+$",
        "variant_regex": "",
        "addons": [],
        "is_glossary": "false",
        "glossary_color": "silver",
    },
    "language_code": "de",
    "id": 98,
    "filename": "ts/de.ts",
    "revision": "49eee4aa551662849f43eaf3e965a26bb08f8a2a",
    "web_url": "http://weblate/projects/test-project/test-component/de/",
    "share_url": "http://weblate/engage/test-project/de/",
    "translate_url": "http://weblate/translate/test-project/test-component/de/",
    "url": "http://weblate/api/translations/test-project/test-component/de/",
    "is_template": "false",
    "is_source": "false",
    "total": 4,
    "total_words": 15,
    "translated": 0,
    "translated_words": 0,
    "translated_percent": 0.0,
    "fuzzy": 0,
    "fuzzy_words": 0,
    "fuzzy_percent": 0.0,
    "failing_checks": 0,
    "failing_checks_words": 0,
    "failing_checks_percent": 0.0,
    "have_suggestion": 0,
    "have_comment": 0,
    # "last_change": "null",
    # "last_author": "null",
    "repository_url": "http://weblate/api/translations/test-project/test-component/de/repository/",
    "file_url": "http://weblate/api/translations/test-project/test-component/de/file/",
    "statistics_url": "http://weblate/api/translations/test-project/test-component/de/statistics/",
    "changes_list_url": "http://weblate/api/translations/test-project/test-component/de/changes/",
    "units_list_url": "http://weblate/api/translations/test-project/test-component/de/units/",
}
