---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: weblatecomponents.loktionovam.com
spec:
  scope: Namespaced
  group: loktionovam.com
  names:
    kind: WeblateComponent
    listKind: WeblateComponentList
    plural: weblatecomponents
    singular: weblatecomponent
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                weblateProjectName:
                  type: string
                weblateComponentRetentionPolicy:
                  type: object
                  properties:
                    whenDeleted:
                      # TODO: validate Retain/Delete
                      type: string
                weblateComponentConfiguration:
                  type: object
                  properties:
                  # ["name", "slug", "file_format", "filemask", "repo"]
                    name:
                      type: string
                    slug:
                      # TODO: create slug as an unchangable
                      type: string
                    projectSlug:
                      type: string
                    fileFormat:
                      type: string
                    fileMask:
                      type: string
                    repo:
                      type: string
                    license:
                      type: string
                    license_url:
                      type: string
                    vcs:
                      type: string
                    branch:
                      type: string
                    newBase:
                      type: string
                  required:
                    - name
                    - slug
                    - projectSlug
                    - fileFormat
                    - fileMask
                    - repo
                    - vcs
                    - branch
                    - newBase
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                message:
                  type: string
