---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: weblatetranslations.loktionovam.com
spec:
  scope: Namespaced
  group: loktionovam.com
  names:
    kind: WeblateTranslation
    listKind: WeblateTranslationList
    plural: weblatetranslations
    singular: weblatetranslation
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                WeblateTranslationRetentionPolicy:
                  type: object
                  properties:
                    whenDeleted:
                      # TODO: validate Retain/Delete
                      type: string
                WeblateTranslationConfiguration:
                  type: object
                  properties:
                    projectSlug:
                      type: string
                    componentSlug:
                      type: string
                    languageCode:
                      type: string
                  required:
                    - name
                    - slug
                    - web
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                message:
                  type: string
